name: Env Demo 

on: [push] 

jobs: 
  demo: 
    runs-on: ubuntu-latest
    environment: dev
    steps: 
      - name: Print the Env variable. 
        run: echo "Greeting from env setting ---> ${{ vars.GREETING }}"
